# Generated by Django 4.1.7 on 2023-03-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolPlanners', '0002_event_subject_current_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolPlanners.assessment')),
            ],
        ),
    ]
