# Generated by Django 4.1.7 on 2023-03-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolPlanners', '0003_homework_completed_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
